language: java

jdk:
- oraclejdk8

script:
- ./gradlew assemble

before_install:
- chmod +x gradlew
before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_deploy:
- "./gradlew showOutput"

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

build:
  stage: build
  script:
    - "./gradlew assemble"
  skip_cleanup: true
  only:
  - master

after_build:
- "./gradlew showOutput"

deploy:
  provider: releases
  api_key:
    secure: I8wvdWN4rjn5hNUulBjtx4ws19uvvdaqfXOC3+8CivF0I0/72DM3zOZlapjhKh9Jt4APoyr1/DOHYwYQyXazs6QzsDKUXDKfn3srdmO7zB/yw5gBYzShFUKWjQDKhj2f0GztaRO6MVD3zhHPAri5mYFThdsGyj9Z//oRjUs/HvD+T80HZG41Cg4Shzciy2FpdYncbC7skxfZfZP5g+GZcnf2ej+ILE4O28HyXqtQQrS+jnTMRVu3BwHotrH/5Xdf6ifDw0AaMELmszPEJ9VkwJT4F+0mDNR0trHizYLYDAu+NFurn/AlGIrUT9Ouu3k/HqMbAFDKx4S9F7zQNMg4jH9QnqHlXxeZVxtzqMityvqlBHcWI0f/5dMUEy2ykN5Cd3RlELKurB1F+PXvPfjjC9xRgB9hbqUo7uOX5jdtwEc/41LXkXGa2d6QwFAaslE/af7IQ+gqY7rtXuvMTjGnDdflY8nJUnsLN4UCq5stvDrvdhOxc/NnukpUJ25miC5giugTCBipxDUQz5zR/dkS2c5f3vgXKzfPEjEDUxGCco06qBCJVPYL+ht5pM2YMGT6ilUrMQZtdhY7By6G0sOdbDIDoBDFneWkfDYY0KWZGwG6QxSc+gFjQS/6iQaqYiLZXuqJtpozLaivbLntEVdnz3L27I5MSqwL/BfiuWCH7ZU=
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true
