language: java
install: true

jdk:
- oraclejdk8

stages:
- build
- test

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: build
    script: ./gradlew build
  - stage: test
    script: ./gradlew check